version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: boston-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - boston-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: boston-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  boston-data:
